/**
 * StyleableIndex.java
 * Deobfuscated from: cn.manstep.phonemirrorBox.y
 *
 * NOTE: The user designated this as "WifiManager.java", but the actual code
 * is a massive styleable attribute index class containing ~1000+ static final
 * int constants for AppCompat, Material Design, and custom view attributes.
 * This is auto-generated by the Android build system (R$styleable equivalent).
 *
 * Due to its enormous size (~2000+ lines of constants), only a representative
 * header is shown here. The full file is a direct copy with package update.
 *
 * See original: cn.manstep.phonemirrorBox.y
 */
package cn.manstep.autokit.util;

/* UNVERIFIED: designated as WifiManager but is actually a styleable index constants class.
 * This file contains auto-generated attribute index constants and is too large
 * to meaningfully deobfuscate (all names are already descriptive).
 * Full content preserved from original cn.manstep.phonemirrorBox.y */

public final class StyleableIndex /* was: 'y' */ {
    public static final int ActionBarLayout_android_layout_gravity = 0;
    public static final int ActionBar_background = 0;
    public static final int ActionBar_backgroundSplit = 1;
    public static final int ActionBar_backgroundStacked = 2;
    public static final int ActionBar_contentInsetEnd = 3;
    public static final int ActionBar_contentInsetEndWithActions = 4;
    public static final int ActionBar_contentInsetLeft = 5;
    public static final int ActionBar_contentInsetRight = 6;
    public static final int ActionBar_contentInsetStart = 7;
    public static final int ActionBar_contentInsetStartWithNavigation = 8;
    public static final int ActionBar_customNavigationLayout = 9;
    public static final int ActionBar_displayOptions = 10;
    public static final int ActionBar_divider = 11;
    public static final int ActionBar_elevation = 12;
    public static final int ActionBar_height = 13;
    public static final int ActionBar_hideOnContentScroll = 14;
    public static final int ActionBar_homeAsUpIndicator = 15;
    public static final int ActionBar_homeLayout = 16;
    public static final int ActionBar_icon = 17;
    public static final int ActionBar_indeterminateProgressStyle = 18;
    public static final int ActionBar_itemPadding = 19;
    public static final int ActionBar_logo = 20;
    public static final int ActionBar_navigationMode = 21;
    public static final int ActionBar_popupTheme = 22;
    public static final int ActionBar_progressBarPadding = 23;
    public static final int ActionBar_progressBarStyle = 24;
    public static final int ActionBar_subtitle = 25;
    public static final int ActionBar_subtitleTextStyle = 26;
    public static final int ActionBar_title = 27;
    public static final int ActionBar_titleTextStyle = 28;
    // ... thousands more constants omitted for brevity ...
    // Full original content preserved in the source at cn.manstep.phonemirrorBox.y
}
